export const Data = [
  {
    id: 1,
    model_no: "101",
    image: "images/img_1.jpg",
    name: "gardrop",
    oda_tipi: "yatak odası",
    model_tipi: "modern",
    kapak_tipi: "düz",
    kapak_modeli: "101",
    kapak_firması: "dekodoor",
    dolap_sekli: "düz",
    hesap_prg: "cabinet_calculation",
    tip: 1,
    X0: 0,
    Y0: 0,
    Z0: 0,
    X: 2000,
    Y: 2000,
    Z: 600,
    description: "e ",
    brand: "Apple",
    category: "Electronics",
    Price: 89.99,
    countInStock: 3,
    rating: 0,
    numReviews: 0,
    sol_yan: {
      dahil: true,
      tip: 1,
      name: "Sol Yan",
      material_id: 0,
      x0: -991,
      y0: 0,
      z0: 0,
      x: 18,
      y: 2000,
      z: 600,
      xg0: 0,
      xg1: 0,
      zg0: 0,
      zg1: 0,
      yg0: 0,
      yg1: 0,
    },
    sol_pervaz: {
      dahil: false,
      tip: 3,
      name: "Sol Pervaz",
      material_id: 18,
      x0: 0,
      y0: 0,
      z0: 0,
      x: 100,
      y: 500,
      z: 18,
      xg0: 0,
      xg1: 0,
      zg0: 0,
      zg1: 0,
      yg0: 0,
      yg1: 0,
    },
    sag_yan: {
      dahil: true,
      tip: 2,
      name: "Sağ Yan",
      material_id: 18,
      x0: 991,
      y0: 0,
      z0: 0,
      x: 18,
      y: 2000,
      z: 600,
      xg0: 0,
      xg1: 0,
      zg0: 0,
      zg1: 0,
      yg0: 0,
      yg1: 0,
    },
    alt: {
      dahil: true,
      tip: 2,
      name: "Alt",
      material_id: 36,
      x0: 0,
      y0: -882,
      z0: 0,
      x: 1964,
      y: 36,
      z: 600,
      xg0: 0,
      xg1: 0,
      zg0: 0,
      zg1: 0,
      yg0: 0,
      yg1: 0,
    },
    ust: {
      dahil: true,
      tip: 3,
      name: "Üst",
      material_id: 36,
      x0: 0,
      y0: 982,
      z0: 0,
      x: 1964,
      y: 36,
      z: 600,
      xg0: 0,
      xg1: 0,
      zg0: 0,
      zg1: 0,
      yg0: 0,
      yg1: 0,
    },
    baza: {
      dahil: true,
      tip: 3,
      name: "Baza",
      material_id: 18,
      x0: 0,
      y0: -950,
      z0: 281,
      x: 1964,
      y: 100,
      z: 18,
      xg0: 0,
      xg1: 0,
      zg0: 0,
      zg1: 0,
      yg0: 0,
      yg1: 0,
    },
    kapak: [],
    kapak_profil: [],
    cekmece_kapak: [],
    cekmece_kasa: [],
    kayit_ekle_dikey: [],
    kayit_ekle_yatay: [],
    raf: [],
    sag_pervaz: {
      dahil: false,
      tip: 3,
      name: "Sag Pervaz",
      material_id: 18,
      x0: 0,
      y0: 0,
      z0: 0,
      x: 100,
      y: 1000,
      z: 18,
      xg0: 0,
      xg1: 0,
      zg0: 0,
      zg1: 0,
      yg0: 0,
      yg1: 0,
    },
    dikey_bolme: [],
    yatay_bolme: [],
    arkalik: [
      {
        dahil: true,
        tip: 3,
        name: "Arkalık",
        material_id: 18,
        x0: 0,
        y0: 0,
        z0: 0,
        x: 1000,
        y: 1000,
        z: 18,
        xg0: 0,
        xg1: 0,
        zg0: 0,
        zg1: 0,
        yg0: 0,
        yg1: 0,
      },
    ],
    bolge: [],
    parca: [
      {
        tip: 1,
        name: "Sol Yan",
        material_id: 1,
        u1: 0,
        u2: 0,
        x0: -991,
        y0: 0,
        z0: 0,
        x: 18,
        y: 2100,
        z: 600,
      }, //sol_yan
      {
        tip: 2,
        name: "Alt",
        material_id: 1,
        u1: 1,
        u2: 1,
        x0: 0,
        y0: -1041,
        z0: 0,
        x: 1964,
        y: 18,
        z: 600,
      }, //alt
      {
        tip: 2,
        name: "Üst",
        material_id: 1,
        u1: 1,
        u2: 1,
        x0: 0,
        y0: 1041,
        z0: 0,
        x: 1964,
        y: 18,
        z: 600,
      }, //üst
      {
        tip: 1,
        name: "Sağ Yan",
        material_id: 1,
        u1: 0,
        u2: 0,
        x0: 991,
        y0: 0,
        z0: 0,
        x: 18,
        y: 2100,
        z: 600,
      }, //sag_yan
      {
        tip: 1,
        name: "DikeyBolme",
        material_id: 1,
        u1: 0,
        u2: 0,
        x0: 0,
        y0: 0,
        z0: 0,
        x: 18,
        y: 2064,
        z: 600,
      }, //DikeyBolme
      {
        tip: 3,
        name: "kapak",
        material_id: 1,
        u1: 0,
        u2: 0,
        x0: 0,
        y0: 0,
        z0: 291,
        x: 1000,
        y: 2064,
        z: 18,
      }, //Kapak
    ],
  },
];
